

import 'package:flutter/material.dart';
import 'dart:io'; 
import 'dart:async';
// import 'dart:convert'; // Added for jsonDecode
import 'package:file_picker/file_picker.dart';

// Assuming you have defined ApiService and DashboardScreen in other files.
import '../api_services.dart'; 
import 'dashboard.dart'; 

// ====================================================================
// MODEL: DocumentType 
// ====================================================================
class DocumentType {
  final String code; 
  final String name; 
  File? file;
  bool isUploaded; 

  DocumentType({required this.code, required this.name, this.file, this.isUploaded = false});
}

// ====================================================================
// WIDGET 1: DocumentListScreen (Shows the list of requirements)
// ====================================================================
class DocumentListScreen extends StatefulWidget {
  // Assuming Application ID is the ID generated by the backend when the application was first submitted
  final String applicationId; 
  final String businessName; 
  final String documentPurpose; // e.g., 'Registration' or 'Renewal'

  const DocumentListScreen({
    super.key, 
    required this.applicationId,
    required this.businessName,
    required this.documentPurpose,
  });

  @override
  State<DocumentListScreen> createState() => _DocumentListScreenState();
}

class _DocumentListScreenState extends State<DocumentListScreen> {
  List<DocumentType> _requiredDocuments = [];
  bool _isScreenLoading = true;
  
  // NOTE: Deleted the hardcoded _getDocumentsByPurpose method here 
  // as the requirements are now dynamically fetched from the API.

  // --- Initialization Logic ---
  @override
  void initState() {
    super.initState();
    // Start fetching the document list and their current upload status
    _fetchRequirementsAndStatus();
  }
  
  Future<void> _fetchRequirementsAndStatus() async {
    setState(() => _isScreenLoading = true);
    
    try {
      // API call to the Flask backend to get the required list based on purpose
      final response = await ApiService.fetchRequirements(widget.documentPurpose); 

      if (response['status'] == 'success') {
        List<DocumentType> documents = [];
        List<dynamic> reqs = response['requirements'] ?? []; 
        
        for (var req in reqs) {
          documents.add(DocumentType(
            code: req['req_code'], 
            // The name should include the description from the database
            name: req['description'], 
            // In a production app, you would check a separate API endpoint here
            // to set isUploaded: true if a file for this req_code exists for this applicationId.
            isUploaded: req.containsKey('is_uploaded') ? (req['is_uploaded'] == 1) : false, 
          ));
        }

        if(mounted) {
          setState(() {
            _requiredDocuments = documents;
            _isScreenLoading = false;
          });
        }
      } else {
        // Handle API failure
        if(mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text(response['message'] ?? 'Failed to load requirements.')),
          );
          setState(() {
            _isScreenLoading = false;
          });
        }
      }
    } catch (e) {
      if(mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error contacting server: $e')),
        );
        setState(() {
          _isScreenLoading = false;
        });
      }
    }
  }

  String _getConditionalLabel(String reqCode, String documentPurpose) {
    // 1. Conditional based on Business Type/Status
    switch (reqCode) {
      case 'CONTRACT_LEASE':
      case 'LESSOR_BP':
        return 'Required if Property is Rented (Lessee)';
      case 'MAFSO_CERT':
        return 'Required for Fishing/Fish Pond Business';
      case 'PNP_CL':
      case 'OR_CR':
      case 'TA_CERT':
        return 'Required for Transport Operation';
    }

    // 2. Conditional based on Application Type (to highlight specific renewal/retirement docs)
    if (documentPurpose == 'Renewal') {
      if (reqCode == 'ITR_VAT') return 'Renewal Specific Document';
    } else if (documentPurpose == 'Retirement') {
      if (reqCode == 'ORIGINAL_PERMIT' || reqCode == 'LETTER_REQUEST' || reqCode == 'BRGY_CLOSURE' || reqCode == 'CLOSED_PIC') {
        return 'Retirement Specific Document';
      }
    }
    
    return ''; // Default for core/general requirements
  }

  // --- Utility: Check if all required documents have been uploaded ---
  bool get _isAllUploaded => _requiredDocuments.every((doc) => doc.isUploaded);
  
  void _finalizeSubmission() {
    // This marks the end of the process (Final Submit button)
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text('Application marked as submitted! Pending review.')),
    );
    if (!mounted) return;
    // Navigates back to the Dashboard/Home
    // Assuming DashboardScreen.routeName is correctly defined
    Navigator.popUntil(context, (route) => route.isFirst || route.settings.name == DashboardScreen.routeName); 
  }

  // --- Navigation to Picker Screen ---
  void _navigateToPicker(DocumentType doc) {
    Navigator.push(
      context,
      MaterialPageRoute(
        builder: (_) => DocumentPickerScreen(
          applicationId: widget.applicationId,
          document: doc, 
          documentPurpose: widget.documentPurpose,
        ),
      ),
    ).then((result) {
      // Logic to update the list view when returning from the picker screen
      if (result == true) {
        // Signal a successful upload was completed
        final index = _requiredDocuments.indexWhere((d) => d.code == doc.code);
        if (index != -1) {
          setState(() {
            _requiredDocuments[index].isUploaded = true;
          });
        }
      }
    });
  }

  // --- UI Build ---
  @override
  Widget build(BuildContext context) {
    if (_isScreenLoading) {
      return const Scaffold(appBar: DocumentsAppBar(title: 'Loading...'), body: Center(child: CircularProgressIndicator()));
    }
    
    return Scaffold(
      appBar: DocumentsAppBar(title: '${widget.documentPurpose} Requirements'),
      
      // Floating button visible only when all documents are uploaded
      floatingActionButton: _isAllUploaded ? FloatingActionButton.extended(
        onPressed: _finalizeSubmission,
        label: const Text('Finalize Submission', style: TextStyle(fontSize: 16)),
        icon: const Icon(Icons.send),
        backgroundColor: Colors.green,
      ) : null,
      floatingActionButtonLocation: FloatingActionButtonLocation.centerFloat,

      body: Column(
        children: [
          Padding(
            padding: const EdgeInsets.all(16.0),
            child: Text(
              'Upload requirements for ${widget.documentPurpose} ID: ${widget.applicationId}',
              style: TextStyle(fontSize: 16, fontWeight: FontWeight.w500, color: _isAllUploaded ? Colors.green : Colors.black),
              textAlign: TextAlign.center,
            ),
          ),
          
          Expanded(
            child: ListView.builder(
              padding: const EdgeInsets.symmetric(horizontal: 16.0),
              itemCount: _requiredDocuments.length,
              itemBuilder: (context, index) {
                final doc = _requiredDocuments[index];
                
                final conditionalLabel = _getConditionalLabel(doc.code, widget.documentPurpose);
                
                // Determine the status text (UPLOADED or Tap to upload)
                String statusText = doc.isUploaded ? 'Status: UPLOADED.' : 'Tap here to upload';
                
                // Construct the final subtitle: Conditional Label (if exists) + Status Text
                String subtitleText = conditionalLabel.isEmpty 
                    ? statusText 
                    : 'Condition: $conditionalLabel\n$statusText'; // Prepend with a label
                    
                return Card(
                  margin: const EdgeInsets.symmetric(vertical: 6),
                  elevation: 1,
                  child: ListTile(
                    leading: Icon(
                      doc.isUploaded ? Icons.check_circle : Icons.upload_file,
                      color: doc.isUploaded ? Colors.green : Colors.orange,
                    ),
                    title: Text(doc.name, style: TextStyle(fontWeight: doc.isUploaded ? FontWeight.bold : FontWeight.w500)),
                    subtitle: Text(doc.isUploaded ? 'Status: UPLOADED.' : 'Tap here to upload',
                      style: TextStyle(color: doc.isUploaded ? Colors.green.shade700 : Colors.grey),
                    ),
                    trailing: const Icon(Icons.arrow_forward_ios), 
                    onTap: () => _navigateToPicker(doc), 
                  ),
                );
              },
            ),
          ),
          
          // Exit button (kept outside of the FAB for accessibility)
          Padding(
            padding: const EdgeInsets.only(left: 16, right: 16, bottom: 16, top: 8), 
            child: TextButton(
              onPressed: () {
                Navigator.popUntil(context, (route) => route.isFirst || route.settings.name == DashboardScreen.routeName);
              },
              child: const Text(
                'Exit to Dashboard (Save Progress)',
                style: TextStyle(color: Colors.red, decoration: TextDecoration.underline)
              ),
            ),
          ),
        ], // End of main Column children
      ), // End of Column
    );
  }
}


// ====================================================================
// WIDGET 2: DocumentPickerScreen (Handles single file selection/upload)
// ====================================================

class DocumentPickerScreen extends StatefulWidget {
  final String applicationId; 
  final DocumentType document;
  final String documentPurpose; 

  const DocumentPickerScreen({
    super.key, 
    required this.applicationId, 
    required this.document,
    required this.documentPurpose,
  });

  @override
  State<DocumentPickerScreen> createState() => _DocumentPickerScreenState();
}

class _DocumentPickerScreenState extends State<DocumentPickerScreen> {
  File? _selectedFile;
  bool _isUploading = false;

  // --- File Picker Logic ---
  Future<void> _pickFile() async {
    FilePickerResult? result = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowedExtensions: const ['pdf', 'jpg', 'jpeg', 'png'],
    );

    if (result != null && result.files.single.path != null) {
      if (!mounted) return;
      setState(() {
        _selectedFile = File(result.files.single.path!);
      });
    }
  }

  // --- Upload Logic ---
  Future<void> _uploadDocument() async {
    if (_selectedFile == null) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Please select a file first.')));
      return;
    }
    if (!mounted) return;
    
    setState(() => _isUploading = true);

    try {
      final response = await ApiService.uploadDocument(
        applicationId: widget.applicationId, 
        documentName: widget.document.code, 
        file: _selectedFile!,
        documentPurpose: widget.documentPurpose,
      );

      if (!mounted) return; 

      if (response['status'] == 'success') {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('${widget.document.name} uploaded successfully!')),
        );
        // Signal success (true) to the parent list screen
        Navigator.pop(context, true); 
      } else {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(response['message'] ?? 'Upload failed.')),
        );
      }
    } catch (e) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Upload Error: ${e.toString()}')));
    } finally {
      if (!mounted) return;
      setState(() => _isUploading = false);
    }
  }

  // --- UI Build ---
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.document.name)),
      body: Padding(
        padding: const EdgeInsets.all(24),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            const Text('Requirement:', style: TextStyle(fontSize: 16)),
            Text(widget.document.name, style: const TextStyle(fontSize: 22, fontWeight: FontWeight.bold)),
            const SizedBox(height: 40),

            // File Selection Button
            ElevatedButton.icon(
              onPressed: _isUploading ? null : _pickFile,
              icon: const Icon(Icons.folder_open),
              label: const Text('Select File'),
              style: ElevatedButton.styleFrom(padding: const EdgeInsets.symmetric(vertical: 15)),
            ),
            const SizedBox(height: 20),

            // Display Selected File Status
            Container(
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(border: Border.all(color: Colors.grey.shade300), borderRadius: BorderRadius.circular(8)),
              child: Text(_selectedFile == null ? 'No file selected.' : 'File Ready: ${_selectedFile!.path.split('/').last}'),
            ),
            const SizedBox(height: 40),

            // Upload Button
            ElevatedButton(
              onPressed: (_selectedFile != null && !_isUploading) ? _uploadDocument : null,
              style: ElevatedButton.styleFrom(backgroundColor: Colors.blue, foregroundColor: Colors.white, padding: const EdgeInsets.symmetric(vertical: 18)),
              child: _isUploading ? const CircularProgressIndicator(color: Colors.white) : const Text('Upload & Save', style: TextStyle(fontSize: 18)),
            ),
          ],
        ),
      ),
    );
  }
}

// Simple AppBar helper (Included for completeness)
class DocumentsAppBar extends StatelessWidget implements PreferredSizeWidget {
  final String title;
  const DocumentsAppBar({super.key, required this.title});

  @override
  Widget build(BuildContext context) {
    return AppBar(
      title: Text(title, style: const TextStyle(color: Colors.white)),
      backgroundColor: const Color(0xFF1A2B47),
      iconTheme: const IconThemeData(color: Colors.white),
    );
  }

  @override
  Size get preferredSize => const Size.fromHeight(kToolbarHeight);
}
// import 'package:flutter/material.dart';
// import 'dart:io'; 
// import 'package:file_picker/file_picker.dart';
// import '../api_services.dart'; // For API methods
// import 'dashboard.dart'; // For navigating back to DashboardScreen

// // ====================================================================
// // MODEL: DocumentType 
// // ====================================================================
// class DocumentType {
//   final String code; 
//   final String name; 
//   File? file;
//   bool isUploaded; 

//   DocumentType({required this.code, required this.name, this.file, this.isUploaded = false});
// }

// // ====================================================================
// // WIDGET 1: DocumentListScreen (Shows the list of requirements)
// // ====================================================================
// class DocumentListScreen extends StatefulWidget {
//   final String applicationId; 
//   final String businessName; 
//   final String documentPurpose; // e.g., 'Registration' or 'Renewal'

//   const DocumentListScreen({
//     super.key, 
//     required this.applicationId,
//     required this.businessName,
//     required this.documentPurpose,
//   });

//   @override
//   State<DocumentListScreen> createState() => _DocumentListScreenState();
// }

// class _DocumentListScreenState extends State<DocumentListScreen> {
//   List<DocumentType> _requiredDocuments = [];
//   bool _isScreenLoading = true;
  
//   // --- Master Document Definitions (Dynamic Lists) ---
//   List<DocumentType> _getDocumentsByPurpose(String purpose) {
//       if (purpose == 'Registration') {
//           return [
//               DocumentType(code: 'CTC', name: '1. Community Tax Certificate (Cedula)'),
//               DocumentType(code: 'BRGY_CLEARANCE', name: '2. Barangay Clearance'),
//               DocumentType(code: 'BRGY_PERMIT', name: '3. Barangay Business Permit'),
//               DocumentType(code: 'DTI_SEC', name: '4. DTI Certification / SEC'),
//               DocumentType(code: 'LANDHOLDINGS', name: '5. Landholdings certificate'),
//               DocumentType(code: 'SANITARY_HEALTH', name: '6. Sanitary Permit/Health Certificate'),
//               DocumentType(code: 'MENRO', name: '7. MENRO Certificate'),
//               DocumentType(code: 'FIRE_SAFETY', name: '8. Fire Safety Inspection Certificate'),
//               DocumentType(code: 'SEPD', name: '9. SEPD certification'),
//           ];
//       } else if (purpose == 'Renewal') {
//           return [
//               DocumentType(code: 'CTC', name: '1. Community Tax Certificate (Cedula)'),
//               DocumentType(code: 'PREVIOUS_PERMIT', name: '2. Copy of Previous Year’s Permit'),
//               DocumentType(code: 'LATEST_ITR', name: '3. Latest Audited Financial Statement/ITR'),
//           ];
//       }
//       return const [];
//   }

//   // --- Initialization Logic ---
//   @override
//   void initState() {
//     super.initState();
//     _fetchRequirementsAndStatus();
//   }
  
//   Future<void> _fetchRequirementsAndStatus() async {
//     setState(() => _isScreenLoading = true);
    
//     // Selects the correct list based on the widget parameter
//     List<DocumentType> documents = _getDocumentsByPurpose(widget.documentPurpose);
    
//     // Simulate API call to check existing status or load (0.5 second delay)
//     await Future.delayed(const Duration(milliseconds: 500)); 

//     if(mounted) {
//       setState(() {
//         _requiredDocuments = documents;
//         _isScreenLoading = false;
//       });
//     }
//   }

//   // --- Utility: Check if all required documents have been uploaded ---
//   bool get _isAllUploaded => _requiredDocuments.every((doc) => doc.isUploaded);
  
//   void _finalizeSubmission() {
//     // This marks the end of the process (Final Submit button)
//     ScaffoldMessenger.of(context).showSnackBar(
//         SnackBar(content: Text('${widget.documentPurpose} application submitted and pending review!')),
//     );
//     if (!mounted) return;
//     // Navigates back to the Dashboard/Home
//     Navigator.popUntil(context, (route) => route.isFirst || route.settings.name == DashboardScreen.routeName);
//   }

//   // --- Navigation to Picker Screen ---
//   void _navigateToPicker(DocumentType doc) {
//     Navigator.push(
//       context,
//       MaterialPageRoute(
//         builder: (_) => DocumentPickerScreen(
//           applicationId: widget.applicationId,
//           document: doc, 
//           documentPurpose: widget.documentPurpose, // Passed down
//         ),
//       ),
//     ).then((result) {
//       // Logic to update the list view when returning from the picker screen
//       if (result == true) {
//         // Find the index of the document that was just uploaded
//         final index = _requiredDocuments.indexWhere((d) => d.code == doc.code);
//         if (index != -1) {
//           setState(() {
//             _requiredDocuments[index].isUploaded = true;
//           });
//         }
//       }
//     });
//   }

//   // --- UI Build ---
// @override
// Widget build(BuildContext context) {
//     if (_isScreenLoading) {
//       return const Scaffold(appBar: DocumentsAppBar(title: 'Loading...'), body: Center(child: CircularProgressIndicator()));
//     }
    
//     return Scaffold(
//       appBar: DocumentsAppBar(title: '${widget.documentPurpose} Requirements'),
      
//       // Floating button visible only when all documents are uploaded
//       floatingActionButton: _isAllUploaded ? FloatingActionButton.extended(
//         onPressed: _finalizeSubmission,
//         label: const Text('Finalize Submission', style: TextStyle(fontSize: 16)),
//         icon: const Icon(Icons.send),
//         backgroundColor: Colors.green,
//       ) : null,
//       floatingActionButtonLocation: FloatingActionButtonLocation.centerFloat,

//       body: Column(
//         children: [
//           Padding(
//             padding: const EdgeInsets.all(16.0),
//             child: Text(
//               'Upload requirements for ${widget.documentPurpose} ID: ${widget.applicationId}',
//               style: TextStyle(fontSize: 16, fontWeight: FontWeight.w500, color: _isAllUploaded ? Colors.green : Colors.black),
//               textAlign: TextAlign.center,
//             ),
//           ),
          
//           Expanded(
//             child: ListView.builder(
//               padding: const EdgeInsets.symmetric(horizontal: 16.0),
//               itemCount: _requiredDocuments.length,
//               itemBuilder: (context, index) {
//                 final doc = _requiredDocuments[index];
                
//                 return Card(
//                   margin: const EdgeInsets.symmetric(vertical: 6),
//                   elevation: 1,
//                   child: ListTile(
//                     leading: Icon(
//                       doc.isUploaded ? Icons.check_circle : Icons.upload_file,
//                       color: doc.isUploaded ? Colors.green : Colors.orange,
//                     ),
//                     title: Text(doc.name, style: TextStyle(fontWeight: doc.isUploaded ? FontWeight.bold : FontWeight.w500)),
//                     subtitle: Text(doc.isUploaded ? 'Status: UPLOADED.' : 'Tap here to upload',
//                       style: TextStyle(color: doc.isUploaded ? Colors.green.shade700 : Colors.grey),
//                     ),
//                     trailing: const Icon(Icons.arrow_forward_ios), 
//                     onTap: () => _navigateToPicker(doc), 
//                   ),
//                 );
//               },
//             ),
//           ),
        
//           Padding(
//             padding: const EdgeInsets.only(left: 16, right: 16, bottom: 16, top: 8), 
//             child: TextButton(
//               onPressed: _finalizeSubmission,
//               child: const Text(
//                 'Exit to Dashboard (Save Progress)',
//                 style: TextStyle(color: Colors.red, decoration: TextDecoration.underline)
//               ),
//             ),
//           ),
//         ], // End of main Column children
//       ), // End of Column
//     );
//   }
//  } // End of Scaffold


// // ====================================================================
// // WIDGET 2: DocumentPickerScreen (Handles single file selection/upload)
// // ====================================================================

// class DocumentPickerScreen extends StatefulWidget {
//   final String applicationId; 
//   final DocumentType document;
//   final String documentPurpose; 

//   const DocumentPickerScreen({
//     super.key, 
//     required this.applicationId, 
//     required this.document,
//     required this.documentPurpose,
//   });

//   @override
//   State<DocumentPickerScreen> createState() => _DocumentPickerScreenState();
// }

// class _DocumentPickerScreenState extends State<DocumentPickerScreen> {
//   File? _selectedFile;
//   bool _isUploading = false;

//   // --- File Picker Logic (omitted for brevity) ---
//   Future<void> _pickFile() async {
//     FilePickerResult? result = await FilePicker.platform.pickFiles(
//       type: FileType.custom,
//       allowedExtensions: const ['pdf', 'jpg', 'jpeg', 'png'],
//     );

//     if (result != null && result.files.single.path != null) {
//       if (!mounted) return;
//       setState(() {
//         _selectedFile = File(result.files.single.path!);
//       });
//     }
//   }

//   // --- Upload Logic ---
//   Future<void> _uploadDocument() async {
//     if (_selectedFile == null) return;
//     if (!mounted) return;
    
//     setState(() => _isUploading = true);

//     try {
//       final response = await ApiService.uploadDocument(
//         applicationId: widget.applicationId, 
//         documentName: widget.document.code, 
//         file: _selectedFile!,
//         documentPurpose: widget.documentPurpose, // Sent to backend
//       );

//       if (!mounted) return; 

//       if (response['status'] == 'success') {
//         ScaffoldMessenger.of(context).showSnackBar(
//           SnackBar(content: Text('${widget.document.name} uploaded successfully!')),
//         );
//         // Signal success (true) to the parent list screen
//         Navigator.pop(context, true); 
//       } else {
//         ScaffoldMessenger.of(context).showSnackBar(
//           SnackBar(content: Text(response['message'] ?? 'Upload failed.')),
//         );
//       }
//     } catch (e) {
//         ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Upload Error: $e')));
//     } finally {
//       if (!mounted) return;
//       setState(() => _isUploading = false);
//     }
//   }

//   // --- UI Build ---
//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       appBar: AppBar(title: Text(widget.document.name)),
//       body: Padding(
//         padding: const EdgeInsets.all(24),
//         child: Column(
//           crossAxisAlignment: CrossAxisAlignment.stretch,
//           children: [
//             const Text('Requirement:', style: TextStyle(fontSize: 16)),
//             Text(widget.document.name, style: const TextStyle(fontSize: 22, fontWeight: FontWeight.bold)),
//             const SizedBox(height: 40),

//             // File Selection Button
//             ElevatedButton.icon(
//               onPressed: _isUploading ? null : _pickFile,
//               icon: const Icon(Icons.folder_open),
//               label: const Text('Select File'),
//               style: ElevatedButton.styleFrom(padding: const EdgeInsets.symmetric(vertical: 15)),
//             ),
//             const SizedBox(height: 20),

//             // Display Selected File Status
//             Container(
//               padding: const EdgeInsets.all(12),
//               decoration: BoxDecoration(border: Border.all(color: Colors.grey.shade300), borderRadius: BorderRadius.circular(8)),
//               child: Text(_selectedFile == null ? 'No file selected.' : 'File Ready: ${_selectedFile!.path.split('/').last}'),
//             ),
//             const SizedBox(height: 40),

//             // Upload Button
//             ElevatedButton(
//               onPressed: (_selectedFile != null && !_isUploading) ? _uploadDocument : null,
//               style: ElevatedButton.styleFrom(backgroundColor: Colors.blue, foregroundColor: Colors.white, padding: const EdgeInsets.symmetric(vertical: 18)),
//               child: _isUploading ? const CircularProgressIndicator(color: Colors.white) : const Text('Upload & Save', style: TextStyle(fontSize: 18)),
//             ),
//           ],
//         ),
//       ),
//     );
//   }
// }

// // Simple AppBar helper (Included for completeness)
// class DocumentsAppBar extends StatelessWidget implements PreferredSizeWidget {
//   final String title;
//   const DocumentsAppBar({super.key, required this.title});

//   @override
//   Widget build(BuildContext context) {
//     return AppBar(
//       title: Text(title, style: const TextStyle(color: Colors.white)),
//       backgroundColor: const Color(0xFF1A2B47),
//       iconTheme: const IconThemeData(color: Colors.white),
//     );
//   }

//   @override
//   Size get preferredSize => const Size.fromHeight(kToolbarHeight);
// }